version: "3.9"
services:
  back:
    image: kemonize/coyote_gin
    build:
      context: ../
      dockerfile: dockerfile/Dockerfile
    # デプロイ後環境変数を合わせるためにsecrets/firebase_credentials.jsonを環境変数に登録
    env_file:
      - ../.env
    ports:
      - 3000:3000
    volumes:
      - ../workdir:/home/workdir
    working_dir: /home/workdir
    container_name: coyote_gin
    command: sh -c "tail -f /dev/null"
    networks:
    - kemonizeTyping

networks:
  kemonizeTyping:
    external: true