version: "3.9"
services:
  back:
    image: kemonize/coyote_gin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../workdir:/home/workdir
    working_dir: /home/workdir
    container_name: coyote_gin
    command: sh -c "tail -f /dev/null"