name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        export TAG=${{ github.sha }}
        docker-compose -f dockerfile_prod/docker-compose.yml build
        docker-compose -f dockerfile_prod/docker-compose.yml push

    - name: Deploy to Azure
      # run: |
      #   az container delete --resource-group my-container-app --name container-app-test --yes
      #   az container create --resource-group my-container-app --name container-app-test --image kemonize/gin_test:${{ github.sha }} --cpu 0.25 --memory 0.5
      run: |
          az containerapp up \
          --name my-container-app \
          --image kemonize/gin_test:${{ github.sha }} \
          --resource-group my-container-app \
          --environment container-app-test \
          --ingress external \
          --target-port 3000